### PR TITLE
allow signature external to the assertion

### LINKED ISSUE #57: signature check fails if whole response is signed
Google Apps for business has a SSO app you can add that is a SAML 2.0 IdP. Google doesn't sign just the assertion, it signs the whole response, so the signature check fails in `saml2-js`.

Google's xml has a `<Reference>` in the `<Signature>` that points to the `id` of the root tag, and `xml-crypto` looks like it correctly handles this; when I hacked `saml2-js` to check the whole doc instead of just the `<Assertion>` it passed.
[zip of Google's SAML response](https://github.com/Clever/saml2/files/166161/google_apps.xml.zip)

### PR DESCRIPTION
**Pull request by chad3814**
- this should fix #57 and #48; see them for comments

### CODE REVIEW

**Comment by jefff** [comment]
Thanks for the PR! Sorry for the delay in reviewing this.

As a minor change, can you flip the order of the two signature checks in the `or` so the current behavior is preserved in the default case? In practice, I don't think it actually matters, but it would make me a bit more confident in releasing this as a minor version bump.

**Comment by chad3814** [comment]
Sure, just adds an additional path

**Comment by jefff** [comment]
Thanks, lgtm!

**Comment by jefff** [comment]
Published as 1.5.0

**Pull request merged**
