### PR TITLE
Update xmldom to use @xmldom/xmdom

### PR DESCRIPTION
**Pull request by nurub52**
we are getting flagged for vulnerability as xmldom dependency is not pointing to new location.

### CODE REVIEW

**Comment by AMEYCHAVAN** [comment]
Hello All
Is anyone looking into this?

**Comment by bnielsen1965** [comment]
Any chance this can get merged? I can help with testing if that is the hold up.

**Comment by syadav214** [comment]
Hey, Please merge it

**Comment by dbauszus-glx** [comment]
Would be great to get this merged. Thanks everyone for looking into this.

**Comment by mcab** [comment]
Closed by https://github.com/Clever/saml2/pull/261.

**Pull request closed without merging**
